name: recipes_app
description: Sample Recipes App

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  dynamic_color: ^1.7.0
  animations: ^2.0.8
  dio: ^5.4.3+1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  dart_code_metrics: ^5.7.6

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          style: normal
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          style: normal
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          style: italic
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          style: normal
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          style: italic
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          style: normal
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          style: normal
        - asset: assets/fonts/Poppins-LightItalic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          style: normal
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          style: normal
        - asset: assets/fonts/Poppins-SemiBold.ttf
          style: normal
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Thin.ttf
          style: normal
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          style: italic
